### ISSUE TITLE
ansible.utils.ipaddr('private') filter fails with AttributeError: 'IPAddress' object has no attribute 'is_global' 

### ISSUE THREAD

**Issue by lewandom** [ansible-collections/ansible.utils#346]
##### SUMMARY
`ansible.utils.ipaddr` filter when called with `private` parameter fails with an error: `AttributeError: 'IPAddress' object has no attribute 'is_global'`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ipaddr filter

##### ANSIBLE VERSION
```
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/redacted/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.5 (main, Sep 22 2023, 15:34:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
# /home/redacted/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 6.0.0  
ansible.posix     1.5.4  
ansible.utils     4.0.0  
community.general 8.2.0
```

##### CONFIGURATION
```
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT
```
Linux redacted 4.18.0-513.11.1.el8_9.x86_64 #1 SMP Thu Dec 7 03:06:13 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE
Just run the ansible.utils.ipaddr filter with 'private' parameter provided, e.g. `ansible -m debug -a "msg={{ '172.16.0.0' | ansible.utils.ipaddr('private') }}"`.

##### EXPECTED RESULTS
```
$ ansible -m debug -a "msg={{ '172.16.0.0' | ansible.utils.ipaddr('private') }}" localhost
localhost | SUCCESS => {
    "msg": "172.16.0.0"
}
```

##### ACTUAL RESULTS
```
$ ansible -vvvv -m debug -a "msg={{ '172.16.0.0' | ansible.utils.ipaddr('private') }}" localhost
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/redacted/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.5 (main, Sep 22 2023, 15:34:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python3.11/site-packages/ansible/plugins/callback/minimal.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Loading collection ansible.utils from /home/redacted/.ansible/collections/ansible_collections/ansible/utils
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ansible/executor/task_executor.py", line 505, in _execute
    self._task.post_validate(templar=templar)
  File "/usr/lib/python3.11/site-packages/ansible/playbook/task.py", line 291, in post_validate
    super(Task, self).post_validate(templar)
  File "/usr/lib/python3.11/site-packages/ansible/playbook/base.py", line 536, in post_validate
    value = templar.template(getattr(self, name))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/template/__init__.py", line 750, in template
    d[k] = self.template(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/template/__init__.py", line 724, in template
    result = self.do_template(
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/template/__init__.py", line 987, in do_template
    res = self.environment.concat(rf)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ansible/template/native_helpers.py", line 44, in ansible_eval_concat
    head = list(islice(nodes, 2))
           ^^^^^^^^^^^^^^^^^^^^^^
  File "<template>", line 17, in root
  File "/usr/lib/python3.11/site-packages/ansible/template/__init__.py", line 262, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/.ansible/collections/ansible_collections/ansible/utils/plugins/filter/ipaddr.py", line 283, in _ipaddr
    return ipaddr(**updated_data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/.ansible/collections/ansible_collections/ansible/utils/plugins/plugin_utils/base/ipaddr_utils.py", line 573, in ipaddr
    return query_func_map[query](v, *extras)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/.ansible/collections/ansible_collections/ansible/utils/plugins/plugin_utils/base/ipaddr_utils.py", line 292, in _private_query
    if not v.ip.is_global():
           ^^^^^^^^^^^^^^
AttributeError: 'IPAddress' object has no attribute 'is_global'
localhost | FAILED! => {
    "changed": false
}
```

**Comment by Ruchip16** [comment]
Starting with ansible.utils v4.0.0, the minimum required netaddr version is  >0.10.1. Reference: https://github.com/ansible-collections/ansible.utils/pull/338

**Comment by Ruchip16** [comment]
@lewandom what version of netaddr are you using?

**Comment by lewandom** [comment]
@Ruchip16 thanks for fast response!

Indeed, we use version 0.8.0 installed from rpms provided from EPEL, and that's the newest version there:
```
$ rpm -qa | grep netaddr
python3.11-netaddr-0.8.0-2.el8.noarch
$ yum list --showduplicates python3.11-netaddr
Installed Packages
python3.11-netaddr.noarch                                                                                                  0.8.0-2.el8                                                                                                   @epel
Available Packages
python3.11-netaddr.noarch                                                                                                  0.8.0-2.el8                                                                                                   epel 
```

It'd be a good idea if the ipaddr filter could tolerate older netaddr versions. E.g. if `is_global` method is not defined, fall back to `is_private`.

**Comment by Ruchip16** [comment]
@lewandom `is_private` is now a deprecated method and thats why upgrading netaddr to its latest version could most probably solve your issue, could you please try to update netaddr once ?

**Comment by lewandom** [comment]
@Ruchip16 I'm sure it would help, but it's not possible with the yum-based python package installation method, at least not until EPEL releases an updated version for the python3.11-netaddr package. Which is not certain it'll ever happen, given that netaddr version 1.0.0 has backwards-incompatible changes.

I created PR #348 to implement a fallback use of is_private() method when is_public() is not available. Please let me know if such solution would be acceptable.

**Comment by Ruchip16** [comment]
Thank you @lewandom for raising the PR,  i would take a look at it and get back to you.
